#!/bin/bash
# data-pipeline/scripts/4_load_data.sh

export MSYS_NO_PATHCONV=1

# This script loads data generated by Phase 3 into MongoDB and Neo4j.
# It assumes it is run from the /etl directory.

set -e # Exit immediately if a command exits with a non-zero status.

# Configuration
COMPOSE_FILE="../../deployment/docker-compose.local.yml"
# Absolute path for the MongoDB import files on the host machine
MONGO_IMPORT_DIR="$(pwd)/import_files/mongodb"
# Path inside the Neo4j container (as defined in docker-compose)
NEO4J_IMPORT_DIR="/var/lib/neo4j/import"

# Load environment variables (for credentials) from the project root
ENV_FILE="../../.env"
if [ -f "${ENV_FILE}" ]; then
  # Export variables from .env file safely
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
else
  echo "Error: .env file not found at ${ENV_FILE}."
  exit 1
fi

# Check if the import files exist
if [ ! -d "$MONGO_IMPORT_DIR" ]; then
    echo "Error: Import directory not found at $MONGO_IMPORT_DIR"
    echo "Please run Phase 3 first."
    exit 1
fi

# Use the DB name defined in the .env file
DB_NAME=${MONGO_DB_NAME}

echo "--- Starting Phase 4: Data Loading ---"

# --- MongoDB Loading (mongoimport) ---
echo "1. Starting MongoDB import into database: ${DB_NAME}..."

# We use 'docker compose run' to launch a temporary container based on the 'mongo1' service.
# This approach cleanly mounts the import files and provides network access without needing 'docker cp'.

# Define the connection string
MONGO_CONN="--uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo1:27017,mongo2:27017,mongo3:27017/${DB_NAME}?replicaSet=rs0&authSource=admin"

echo "   Importing Authors..."
# Mount the local MongoDB import dir to /import inside the temporary container
# Use --drop to clear the collection before importing.
docker compose -f $COMPOSE_FILE run --rm -v $MONGO_IMPORT_DIR:/import mongo1 mongoimport $MONGO_CONN --collection authors --file /import/authors.jsonl --drop

echo "   Importing Venues..."
docker compose -f $COMPOSE_FILE run --rm -v $MONGO_IMPORT_DIR:/import mongo1 mongoimport $MONGO_CONN --collection venues --file /import/venues.jsonl --drop

echo "   Importing Papers (This might take a while)..."
docker compose -f $COMPOSE_FILE run --rm -v $MONGO_IMPORT_DIR:/import mongo1 mongoimport $MONGO_CONN --collection papers --file /import/papers.jsonl --drop

echo "MongoDB import complete."


# --- Neo4j Loading (neo4j-admin import) ---
# This tool requires the database to be OFFLINE for maximum performance and safety.

echo "2. Starting Neo4j import..."
echo "   Stopping Neo4j container for offline import..."
# Stop the running Neo4j service
docker compose -f $COMPOSE_FILE stop neo4j

echo "   Running neo4j-admin database import (This will take a while)..."

# Run the import command in a temporary container based on the 'neo4j' service definition.
# It shares the volumes (data and import files) with the stopped service.
# We must specify '--user neo4j' to ensure correct permissions on the database files.
# The CSV files generated in Phase 3 already contain the headers required by the tool.
docker compose -f $COMPOSE_FILE run --rm --user neo4j neo4j neo4j-admin database import full \
  --overwrite-destination=true \
  --nodes=Paper=$NEO4J_IMPORT_DIR/nodes_papers.csv \
  --nodes=Author=$NEO4J_IMPORT_DIR/nodes_authors.csv \
  --nodes=Venue=$NEO4J_IMPORT_DIR/nodes_venues.csv \
  --nodes=Topic=$NEO4J_IMPORT_DIR/nodes_topics.csv \
  --relationships=AUTHORED=$NEO4J_IMPORT_DIR/rels_authored.csv \
  --relationships=CITES=$NEO4J_IMPORT_DIR/rels_cites.csv \
  --relationships=PUBLISHED_IN=$NEO4J_IMPORT_DIR/rels_published_in.csv \
  --relationships=HAS_TOPIC=$NEO4J_IMPORT_DIR/rels_has_topic.csv

if [ $? -eq 0 ]; then
    echo "Neo4j import successful."
else
    echo "Error during Neo4j import."
    # Restart the container anyway so the user can debug
    docker compose -f $COMPOSE_FILE start neo4j
    exit 1
fi

echo "   Restarting Neo4j container..."
docker compose -f $COMPOSE_FILE start neo4j

echo "Phase 4: Data Loading Complete."