package it.unipi.nexusscholar.model.mongo;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Field;

/**
 * Abstract base class representing a generic user in the Nexus Scholar system.
 *
 * <p>This class captures the common attributes shared by all user types (e.g., Administrators and
 * Registered Users), such as authentication credentials and system metadata. It is not intended to
 * be instantiated directly but rather extended by concrete document classes.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public abstract class User {

  /**
   * The unique identifier for the user document.
   *
   * <p>Automatically generated by MongoDB upon insertion.
   */
  @Id private String id;

  /**
   * The unique username used for system login.
   *
   * <p>This field must be unique across the entire user collection it belongs to.
   */
  private String username;

  /**
   * The user's contact email address.
   *
   * <p>Used for communication and account recovery. Must be unique.
   */
  private String email;

  /**
   * The encrypted password hash.
   *
   * <p>Stores the BCrypt hash of the user's password. The raw password is never stored. Mapped to
   * the field 'password_hash' in the MongoDB document.
   */
  @Field("password_hash")
  private String password;

  /**
   * The timestamp indicating when the user account was created.
   *
   * <p>Automatically populated by Spring Data MongoDB auditing features when the document is first
   * saved.
   */
  @CreatedDate
  @Field("created_at")
  private LocalDateTime createdAt;
}
